services:

  mongodb:
    image: mongo:8
    container_name: taskhub-mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    cap_drop:
      - ALL

    networks:
      - taskhub

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: obicauka/taskhub-backend:1.1

    container_name: taskhub-backend

    restart: unless-stopped

    depends_on:
      - mongodb

    environment:
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/taskhub?authSource=admin
      JWT_SECRET: ${JWT_SECRET}

    cap_drop:
      - ALL

    networks:
      - taskhub

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: obicauka/taskhub-frontend:1.1

    container_name: taskhub-frontend

    restart: unless-stopped

    depends_on:
      - backend

    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000

    ports:
      - "3000:3000"

    cap_drop:
      - ALL

    networks:
      - taskhub

networks:
  taskhub:

volumes:
  mongodb_data: